import React,{useCallback,useEffect,useState} from "react";
import {Image,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View} from "react-native";
import {getChapters} from "../api/mangadex";
import {getLibrary,removeFromLibrary,updateLibraryEntry} from "../storage/library";
import {colors,radius,spacing} from "../constants/theme";
import type {Chapter,LibraryEntry,ReadingStatus} from "../types/models";
const statuses:ReadingStatus[]=["reading","completed","plan_to_read","dropped"];
export function LibraryScreen(){
 const[entries,setEntries]=useState<LibraryEntry[]>([]);const[filter,setFilter]=useState<ReadingStatus|"all">("all");const[refreshing,setRefreshing]=useState(false);
 const load=useCallback(async()=>setEntries(await getLibrary()),[]);useEffect(()=>{void load()},[load]);
 const refresh=async()=>{setRefreshing(true);await load();setRefreshing(false)};const visible=filter==="all"?entries:entries.filter(e=>e.readingStatus===filter);
 return <ScrollView style={styles.container} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={colors.primary}/>}><Text style={styles.kicker}>LIBRARY</Text><Text style={styles.title}>My Manhwa</Text>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{(["all",...statuses] as const).map(s=><Pressable key={s} onPress={()=>setFilter(s)} style={[styles.chip,filter===s&&styles.active]}><Text style={styles.chipText}>{s==="all"?"All":s==="plan_to_read"?"Plan to Read":s.charAt(0).toUpperCase()+s.slice(1)}</Text></Pressable>)}</ScrollView>
 {visible.length===0?<Text style={styles.empty}>Your library is empty. Add a manhwa from Discover.</Text>:visible.map(entry=><LibraryCard key={entry.manga.id} entry={entry} onUpdate={setEntries}/>)}</ScrollView>;
}
function LibraryCard({entry,onUpdate}:{entry:LibraryEntry;onUpdate:(v:LibraryEntry[])=>void}){
 const[chapters,setChapters]=useState<Chapter[]>([]);const[expanded,setExpanded]=useState(false);const[loading,setLoading]=useState(false);
 const progressIndex=entry.currentChapter?chapters.findIndex(c=>c.chapter===entry.currentChapter):-1;const progress=chapters.length&&progressIndex>=0?Math.round(((chapters.length-progressIndex)/chapters.length)*100):0;
 const loadChapters=async()=>{if(chapters.length){setExpanded(v=>!v);return}setLoading(true);try{setChapters(await getChapters(entry.manga.id,50));setExpanded(true)}finally{setLoading(false)}};
 const markNext=async()=>{if(!chapters.length){await loadChapters();return}const index=entry.currentChapter?chapters.findIndex(c=>c.chapter===entry.currentChapter):-1;const next=chapters[Math.min(index+1,chapters.length-1)];if(next)onUpdate(await updateLibraryEntry(entry.manga.id,{currentChapter:next.chapter,readingStatus:"reading"}))};
 return <View style={styles.card}><View style={styles.row}><View style={styles.coverWrap}>{entry.manga.coverUrl?<Image source={{uri:entry.manga.coverUrl}} style={styles.cover}/>:<View style={[styles.cover,styles.placeholder]}><Text style={styles.coverText}>No Cover</Text></View>}</View><View style={styles.info}><Text style={styles.cardTitle} numberOfLines={2}>{entry.manga.title}</Text><Text style={styles.status}>{entry.readingStatus==="plan_to_read"?"Plan to Read":entry.readingStatus.charAt(0).toUpperCase()+entry.readingStatus.slice(1)}</Text><Text style={styles.chapter}>{entry.currentChapter?"Last read: Chapter "+entry.currentChapter:"Not started"}</Text>{progress>0?<View style={styles.progressTrack}><View style={[styles.progressFill,{width:progress+"%"}]}/></View>:null}{progress>0?<Text style={styles.progressText}>{progress}% chapter progress</Text>:null}</View><Pressable onPress={()=>void removeFromLibrary(entry.manga.id).then(onUpdate)}><Text style={styles.remove}>Remove</Text></Pressable></View>
 <View style={styles.actions}>{statuses.map(s=><Pressable key={s} onPress={()=>void updateLibraryEntry(entry.manga.id,{readingStatus:s}).then(onUpdate)} style={[styles.action,entry.readingStatus===s&&styles.selected]}><Text style={styles.actionText}>{s==="plan_to_read"?"Plan to Read":s.charAt(0).toUpperCase()+s.slice(1)}</Text></Pressable>)}</View>
 <View style={styles.bottomActions}><Pressable onPress={()=>void markNext()} style={styles.chapterButton}><Text style={styles.chapterButtonText}>{loading?"Loading...":entry.currentChapter?"Mark Next Chapter":"Load Chapters"}</Text></Pressable><Pressable onPress={()=>void loadChapters()} style={styles.secondaryButton}><Text style={styles.secondaryText}>{expanded?"Hide Chapters":"View Chapters"}</Text></Pressable></View>
 {expanded?<View style={styles.chapterList}>{chapters.slice(0,20).map(ch=><Pressable key={ch.id} onPress={()=>void updateLibraryEntry(entry.manga.id,{currentChapter:ch.chapter,readingStatus:"reading"}).then(onUpdate)} style={[styles.chapterRow,entry.currentChapter===ch.chapter&&styles.current]}><Text style={styles.chapterName}>Chapter {ch.chapter}</Text><Text style={styles.chapterAction}>{entry.currentChapter===ch.chapter?"Current":"Read"}</Text></Pressable>)}</View>:null}</View>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingBottom:spacing.xxl},kicker:{color:colors.primary,fontSize:12,fontWeight:"800",letterSpacing:1.5},title:{color:colors.text,fontSize:30,fontWeight:"800",marginTop:spacing.xs},filters:{gap:spacing.sm,paddingVertical:spacing.lg},chip:{paddingHorizontal:spacing.md,paddingVertical:spacing.sm,borderRadius:radius.pill,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},active:{backgroundColor:colors.primarySoft,borderColor:colors.primary},chipText:{color:colors.textSecondary,textTransform:"capitalize"},empty:{color:colors.textSecondary,textAlign:"center",marginTop:spacing.xxl},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md,marginBottom:spacing.md},row:{flexDirection:"row",gap:spacing.md},coverWrap:{width:72},cover:{width:72,height:100,borderRadius:radius.sm},placeholder:{backgroundColor:colors.surfaceElevated,alignItems:"center",justifyContent:"center"},coverText:{color:colors.textMuted,fontSize:9},info:{flex:1},cardTitle:{color:colors.text,fontSize:17,fontWeight:"800"},status:{color:colors.primary,textTransform:"capitalize",marginTop:spacing.xs},chapter:{color:colors.textSecondary,fontSize:12,marginTop:spacing.sm},remove:{color:colors.danger,fontWeight:"700"},progressTrack:{height:6,backgroundColor:colors.surfaceElevated,borderRadius:radius.pill,overflow:"hidden",marginTop:spacing.sm},progressFill:{height:"100%",backgroundColor:colors.primary},progressText:{color:colors.textMuted,fontSize:10,marginTop:3},actions:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm,marginTop:spacing.md},action:{borderWidth:1,borderColor:colors.border,borderRadius:radius.sm,paddingHorizontal:spacing.sm,paddingVertical:spacing.xs},selected:{borderColor:colors.primary,backgroundColor:colors.primarySoft},actionText:{color:colors.textSecondary,fontSize:12,textTransform:"capitalize"},bottomActions:{flexDirection:"row",gap:spacing.sm,marginTop:spacing.md},chapterButton:{flex:1,backgroundColor:colors.primarySoft,borderRadius:radius.sm,padding:spacing.sm,alignItems:"center"},chapterButtonText:{color:colors.text,fontWeight:"700",fontSize:12},secondaryButton:{flex:1,borderWidth:1,borderColor:colors.border,borderRadius:radius.sm,padding:spacing.sm,alignItems:"center"},secondaryText:{color:colors.textSecondary,fontWeight:"700",fontSize:12},chapterList:{marginTop:spacing.md,borderTopWidth:1,borderTopColor:colors.border,paddingTop:spacing.sm},chapterRow:{flexDirection:"row",justifyContent:"space-between",paddingVertical:spacing.sm,borderBottomWidth:1,borderBottomColor:colors.border},current:{backgroundColor:colors.primarySoft},chapterName:{color:colors.text,fontWeight:"600"},chapterAction:{color:colors.primary,fontWeight:"700"}});
