import React,{useCallback,useEffect,useState} from "react";
import {Image,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View} from "react-native";
import {getLibrary,removeFromLibrary,updateLibraryEntry} from "../storage/library";
import {colors,radius,spacing} from "../constants/theme";
import type {LibraryEntry,ReadingStatus} from "../types/models";
const statuses:ReadingStatus[]=["reading","completed","plan_to_read","dropped"];
export function LibraryScreen(){
 const[entries,setEntries]=useState<LibraryEntry[]>([]);const[filter,setFilter]=useState<ReadingStatus|"all">("all");const[refreshing,setRefreshing]=useState(false);
 const load=useCallback(async()=>setEntries(await getLibrary()),[]);useEffect(()=>{void load()},[load]);
 const refresh=async()=>{setRefreshing(true);await load();setRefreshing(false)};const visible=filter==="all"?entries:entries.filter(e=>e.readingStatus===filter);
 return <ScrollView style={styles.container} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={colors.primary}/>}><Text style={styles.kicker}>LIBRARY</Text><Text style={styles.title}>My Manhwa</Text>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{(["all",...statuses] as const).map(s=><Pressable key={s} onPress={()=>setFilter(s)} style={[styles.chip,filter===s&&styles.active]}><Text style={styles.chipText}>{s==="all"?"All":s==="plan_to_read"?"Plan to Read":s.charAt(0).toUpperCase()+s.slice(1)}</Text></Pressable>)}</ScrollView>
 {visible.length===0?<Text style={styles.empty}>Your library is empty. Add a manhwa from Discover.</Text>:visible.map(entry=><LibraryCard key={entry.manga.id} entry={entry} onUpdate={setEntries}/>)}</ScrollView>;
}
function LibraryCard({entry,onUpdate}:{entry:LibraryEntry;onUpdate:(v:LibraryEntry[])=>void}){
 const[loading,setLoading]=useState(false);
 const progress=entry.currentChapter&&entry.manga.lastChapter?Math.min(100,Math.round((Number(entry.currentChapter)/Number(entry.manga.lastChapter))*100)):0;
 const markNext=async()=>{const current=Number(entry.currentChapter);const total=Number(entry.manga.lastChapter);const next=Number.isFinite(current)&&current>0?current+1:1;if(Number.isFinite(total)&&total>0&&next>total)return;setLoading(true);try{onUpdate(await updateLibraryEntry(entry.manga.id,{currentChapter:String(next),readingStatus:"reading"}))}finally{setLoading(false)}};
 return <View style={styles.card}><View style={styles.row}><View style={styles.coverWrap}>{entry.manga.coverUrl?<Image source={{uri:entry.manga.coverUrl}} style={styles.cover}/>:<View style={[styles.cover,styles.placeholder]}><Text style={styles.coverText}>No Cover</Text></View>}</View><View style={styles.info}><Text style={styles.cardTitle} numberOfLines={2}>{entry.manga.title}</Text><Text style={styles.status}>{entry.readingStatus==="plan_to_read"?"Plan to Read":entry.readingStatus.charAt(0).toUpperCase()+entry.readingStatus.slice(1)}</Text><Text style={styles.chapter}>{entry.currentChapter?"Last read: Chapter "+entry.currentChapter:"Not started"}</Text>{progress>0?<View style={styles.progressTrack}><View style={[styles.progressFill,{width:progress+"%"}]}/></View>:null}{progress>0?<Text style={styles.progressText}>{progress}% chapter progress</Text>:null}</View><Pressable onPress={()=>void removeFromLibrary(entry.manga.id).then(onUpdate)} hitSlop={2} pressRetentionOffset={0} style={styles.removeButton}><Text style={styles.remove}>Remove</Text></Pressable></View>
 <View style={styles.actions}>{statuses.map(s=><Pressable key={s} onPress={()=>void updateLibraryEntry(entry.manga.id,{readingStatus:s}).then(onUpdate)} style={[styles.action,entry.readingStatus===s&&styles.selected]}><Text style={styles.actionText}>{s==="plan_to_read"?"Plan to Read":s.charAt(0).toUpperCase()+s.slice(1)}</Text></Pressable>)}</View>
 <View style={styles.bottomActions}><Pressable onPress={()=>void markNext()} style={styles.chapterButton}><Text style={styles.chapterButtonText}>{loading?"Saving...":"Mark Next Chapter"}</Text></Pressable></View></View>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingBottom:spacing.xxl},kicker:{color:colors.primary,fontSize:12,fontWeight:"800",letterSpacing:1.5},title:{color:colors.text,fontSize:30,fontWeight:"800",marginTop:spacing.xs},filters:{gap:spacing.sm,paddingVertical:spacing.lg},chip:{paddingHorizontal:spacing.md,paddingVertical:spacing.sm,borderRadius:radius.pill,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},active:{backgroundColor:colors.primarySoft,borderColor:colors.primary},chipText:{color:colors.textSecondary,textTransform:"capitalize"},empty:{color:colors.textSecondary,textAlign:"center",marginTop:spacing.xxl},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md,marginBottom:spacing.md},row:{flexDirection:"row",gap:spacing.md},coverWrap:{width:72},cover:{width:72,height:100,borderRadius:radius.sm},placeholder:{backgroundColor:colors.surfaceElevated,alignItems:"center",justifyContent:"center"},coverText:{color:colors.textMuted,fontSize:9},info:{flex:1},cardTitle:{color:colors.text,fontSize:17,fontWeight:"800"},status:{color:colors.primary,textTransform:"capitalize",marginTop:spacing.xs},chapter:{color:colors.textSecondary,fontSize:12,marginTop:spacing.sm},removeButton:{alignSelf:"flex-start"},remove:{color:colors.danger,fontWeight:"700"},progressTrack:{height:6,backgroundColor:colors.surfaceElevated,borderRadius:radius.pill,overflow:"hidden",marginTop:spacing.sm},progressFill:{height:"100%",backgroundColor:colors.primary},progressText:{color:colors.textMuted,fontSize:10,marginTop:3},actions:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm,marginTop:spacing.md},action:{borderWidth:1,borderColor:colors.border,borderRadius:radius.sm,paddingHorizontal:spacing.sm,paddingVertical:spacing.xs},selected:{borderColor:colors.primary,backgroundColor:colors.primarySoft},actionText:{color:colors.textSecondary,fontSize:12,textTransform:"capitalize"},bottomActions:{flexDirection:"row",gap:spacing.sm,marginTop:spacing.md},chapterButton:{flex:1,backgroundColor:colors.primarySoft,borderRadius:radius.sm,padding:spacing.sm,alignItems:"center"},chapterButtonText:{color:colors.text,fontWeight:"700",fontSize:12}});
