import React,{useCallback,useEffect,useState} from "react";
import {Pressable,RefreshControl,ScrollView,StyleSheet,Text,View} from "react-native";
import {colors,radius,spacing} from "../constants/theme";
import {getActivity,getLibrary} from "../storage/library";
import type {ActivityEvent,LibraryEntry} from "../types/models";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { TimelineStackParamList } from "../navigation/TimelineStackNavigator";

type Props=NativeStackScreenProps<TimelineStackParamList,"TimelineHome">;

export function TimelineScreen({navigation}:Props){
 const[entries,setEntries]=useState<LibraryEntry[]>([]);const[activity,setActivity]=useState<ActivityEvent[]>([]);const[refreshing,setRefreshing]=useState(false);
 const load=useCallback(async()=>{const[library,events]=await Promise.all([getLibrary(),getActivity(20)]);setEntries(library);setActivity(events)},[]);
 useEffect(()=>{void load()},[load]);
 const refresh=async()=>{setRefreshing(true);await load();setRefreshing(false)};
 const reading=entries.filter(e=>e.readingStatus==="reading");const completed=entries.filter(e=>e.readingStatus==="completed");const plan=entries.filter(e=>e.readingStatus==="plan_to_read");const total=entries.length;const progress=total?Math.round((completed.length/total)*100):0;
 return <ScrollView style={styles.container} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={colors.primary}/>}>
  <Text style={styles.kicker}>MANHWATIMELINE</Text><Text style={styles.title}>Your Timeline</Text><Text style={styles.subtitle}>Your reading activity, progress, and next reads.</Text>
  <View style={styles.stats}><Stat label="Library" value={String(total)}/><Stat label="Reading" value={String(reading.length)}/><Stat label="Done" value={String(completed.length)}/></View>
  <View style={styles.progressCard}><View style={styles.row}><Text style={styles.cardTitle}>Library progress</Text><Text style={styles.percent}>{progress}%</Text></View><View style={styles.bar}><View style={[styles.fill,{width:progress+"%"}]}/></View><Text style={styles.muted}>{completed.length} of {total} titles completed</Text></View>
  <Section title="Continue Reading" entries={reading} empty="No manhwa currently marked as Reading." navigation={navigation}/>
  <Section title="Plan to Read" entries={plan} empty="Nothing queued yet." navigation={navigation}/>
  {completed.length>0?<Section title="Completed" entries={completed.slice(0,5)} empty="" navigation={navigation}/>:null}
  <View style={styles.section}><Text style={styles.sectionTitle}>Recent Activity</Text>{activity.length===0?<Text style={styles.empty}>Your reading activity will appear here.</Text>:activity.map(event=><View key={event.id} style={styles.activity}><View style={styles.dot}/><View style={styles.activityInfo}><Text style={styles.itemTitle}>{event.mangaTitle}</Text><Text style={styles.muted}>{event.detail}</Text><Text style={styles.date}>{formatDate(event.createdAt)}</Text></View></View>)}</View>
 </ScrollView>;
}
function formatDate(value:string){const date=new Date(value);return date.toLocaleString(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});}
function Stat({label,value}:{label:string;value:string}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.muted}>{label}</Text></View>}
function Section({title,entries,empty,navigation}:{title:string;entries:LibraryEntry[];empty:string;navigation:Props["navigation"]}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{entries.length===0?<Text style={styles.empty}>{empty}</Text>:entries.map(e=><Pressable key={e.manga.id} onPress={()=>navigation.push("MangaDetail",{manga:e.manga})} style={({pressed})=>[styles.item,pressed&&styles.pressed]}><View style={styles.info}><Text style={styles.itemTitle} numberOfLines={1}>{e.manga.title}</Text><Text style={styles.muted}>{e.currentChapter?"Last read: Chapter "+e.currentChapter:"Not started"}</Text></View><Text style={styles.chevron}>›</Text></Pressable>)}</View>}

function ActivityCard({event,entries,navigation}:{event:ActivityEvent;entries:LibraryEntry[];navigation:Props["navigation"]}){const entry=entries.find(item=>item.manga.id===event.mangaId);const content=<View style={styles.activity}><View style={styles.dot}/><View style={styles.activityInfo}><Text style={styles.itemTitle}>{event.mangaTitle}</Text><Text style={styles.muted}>{event.detail}</Text><Text style={styles.date}>{formatDate(event.createdAt)}</Text></View>{entry?<Text style={styles.chevron}>›</Text>:null}</View>;return entry?<Pressable onPress={()=>navigation.push("MangaDetail",{manga:entry.manga})} style={({pressed})=>[pressed&&styles.pressed]}>{content}</Pressable>:content}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingBottom:spacing.xxl},kicker:{color:colors.primary,fontSize:12,fontWeight:"800",letterSpacing:1.5},title:{color:colors.text,fontSize:30,fontWeight:"800",marginTop:spacing.xs},subtitle:{color:colors.textSecondary,marginTop:spacing.sm,lineHeight:21},stats:{flexDirection:"row",gap:spacing.sm,marginTop:spacing.xl},stat:{flex:1,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md},statValue:{color:colors.text,fontSize:22,fontWeight:"800"},muted:{color:colors.textSecondary,fontSize:12,marginTop:spacing.xs},progressCard:{marginTop:spacing.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md},row:{flexDirection:"row",justifyContent:"space-between"},cardTitle:{color:colors.text,fontWeight:"800"},percent:{color:colors.primary,fontWeight:"800"},bar:{height:8,backgroundColor:colors.surfaceElevated,borderRadius:radius.pill,overflow:"hidden",marginTop:spacing.md},fill:{height:"100%",backgroundColor:colors.primary},section:{marginTop:spacing.xl},sectionTitle:{color:colors.text,fontSize:19,fontWeight:"800",marginBottom:spacing.sm},empty:{color:colors.textMuted,paddingVertical:spacing.sm},item:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md,marginBottom:spacing.sm,flexDirection:"row",alignItems:"center"},info:{flex:1},itemTitle:{color:colors.text,fontWeight:"700",fontSize:15},activity:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md,marginBottom:spacing.sm,flexDirection:"row",gap:spacing.md},dot:{width:9,height:9,borderRadius:9,backgroundColor:colors.primary,marginTop:5},activityInfo:{flex:1},date:{color:colors.textMuted,fontSize:11,marginTop:3},chevron:{color:colors.textMuted,fontSize:24,lineHeight:24},pressed:{opacity:0.72}});
