import type {Manga,MangaStatus} from "../types/models";
const API_URL="https://api.mangadex.org";const COVER_URL="https://uploads.mangadex.org/covers";
type MangaDexTag={id:string;attributes:{name?:Record<string,string>;group?:string}};
type MangaDexManga={id:string;attributes:{title?:Record<string,string>;altTitles?:Array<Record<string,string>>;description?:Record<string,string>;status?:string;year?:number|null;lastChapter?:string|null;lastVolume?:string|null;contentRating?:string;followedCount?:number;createdAt?:string;updatedAt?:string;tags?:MangaDexTag[]};relationships?:Array<{type:string;id:string;attributes?:{name?:string;fileName?:string}}>;};
function pick(record?:Record<string,string>){return record?.en??record?.["ja-ro"]??record?.ja??(record?Object.values(record)[0]:undefined)}
function mapStatus(s?:string):MangaStatus{return s==="ongoing"||s==="completed"||s==="hiatus"||s==="cancelled"?s:"unknown"}
function mapManga(item:MangaDexManga):Manga{const cover=item.relationships?.find(r=>r.type==="cover_art");const authors=item.relationships?.filter(r=>r.type==="author").map(r=>r.attributes?.name).filter((x):x is string=>Boolean(x))??[];const artists=item.relationships?.filter(r=>r.type==="artist").map(r=>r.attributes?.name).filter((x):x is string=>Boolean(x))??[];return{id:item.id,title:pick(item.attributes.title)??"Untitled",altTitles:item.attributes.altTitles?.map(pick).filter((x):x is string=>Boolean(x)),description:pick(item.attributes.description),coverUrl:cover?.attributes?.fileName?COVER_URL+"/"+item.id+"/"+cover.attributes.fileName:undefined,status:mapStatus(item.attributes.status),year:item.attributes.year??undefined,genres:item.attributes.tags?.filter(t=>t.attributes.group==="genre").map(t=>pick(t.attributes.name)).filter((x):x is string=>Boolean(x))??[],authors,artists,lastChapter:item.attributes.lastChapter??undefined,lastVolume:item.attributes.lastVolume??undefined,contentRating:item.attributes.contentRating,followedCount:item.attributes.followedCount,createdAt:item.attributes.createdAt,updatedAt:item.attributes.updatedAt}}
async function request(params:URLSearchParams){const response=await fetch(API_URL+"/manga?"+params.toString());if(!response.ok)throw new Error("MangaDex request failed: "+response.status);const json=await response.json() as {data:MangaDexManga[]};return json.data.map(mapManga)}
export async function getTags(){const response=await fetch(API_URL+"/manga/tag");if(!response.ok)throw new Error("MangaDex tags request failed: "+response.status);const json=await response.json() as {data:MangaDexTag[]};return json.data.filter(t=>t.attributes.group==="genre").map(t=>({id:t.id,name:pick(t.attributes.name)??"Unknown"}))}
const base=(limit:number)=>new URLSearchParams({limit:String(limit),"contentRating[]":"safe","includes[]":"cover_art","includes[1]":"author","includes[2]":"artist"});
export async function getPopularManga(limit=20,genreId?:string){const p=base(limit);p.set("order[followedCount]","desc");if(genreId)p.set("includedTags[]",genreId);return request(p)}
export async function getLatestManga(limit=20,genreId?:string){const p=base(limit);p.set("order[latestUploadedChapter]","desc");if(genreId)p.set("includedTags[]",genreId);return request(p)}
export async function getCompletedManga(limit=20,genreId?:string){const p=base(limit);p.set("status[]","completed");p.set("order[followedCount]","desc");if(genreId)p.set("includedTags[]",genreId);return request(p)}
export async function getOngoingManga(limit=20,genreId?:string){const p=base(limit);p.set("status[]","ongoing");p.set("order[followedCount]","desc");if(genreId)p.set("includedTags[]",genreId);return request(p)}
export async function searchManga(query:string,limit=20,genreId?:string){const p=base(limit);p.set("title",query);p.set("order[relevance]","desc");if(genreId)p.set("includedTags[]",genreId);return request(p)}
