import AsyncStorage from "@react-native-async-storage/async-storage";
import type { ActivityEvent, LibraryEntry, Manga, ReadingStatus } from "../types/models";
const KEY="manhwatimeline.library.v1";
const ACTIVITY_KEY="manhwatimeline.activity.v1";
async function read():Promise<LibraryEntry[]>{const raw=await AsyncStorage.getItem(KEY);if(!raw)return[];try{return JSON.parse(raw) as LibraryEntry[]}catch{return[]}}
async function write(entries:LibraryEntry[]){await AsyncStorage.setItem(KEY,JSON.stringify(entries));}
async function readActivity():Promise<ActivityEvent[]>{const raw=await AsyncStorage.getItem(ACTIVITY_KEY);if(!raw)return[];try{return JSON.parse(raw) as ActivityEvent[]}catch{return[]}}
async function addActivity(event:Omit<ActivityEvent,"id"|"createdAt">){const events=await readActivity();events.unshift({...event,id:Date.now().toString()+"-"+Math.random().toString(36).slice(2),createdAt:new Date().toISOString()});await AsyncStorage.setItem(ACTIVITY_KEY,JSON.stringify(events.slice(0,100)));}
export async function getLibrary(){return read();}
export async function getLibraryEntry(id:string){const entries=await read();return entries.find(entry=>entry.manga.id===id);}
export async function getActivity(limit=30){return (await readActivity()).slice(0,limit);}
export async function addToLibrary(manga:Manga,readingStatus:ReadingStatus="plan_to_read"){const entries=await read();const now=new Date().toISOString();const existing=entries.find(e=>e.manga.id===manga.id);if(existing){const changed=existing.readingStatus!==readingStatus;if(changed){existing.readingStatus=readingStatus;existing.updatedAt=now;await addActivity({type:"status_changed",mangaId:manga.id,mangaTitle:manga.title,detail:"Status changed to "+readingStatus});await write(entries);}}else{entries.unshift({manga,readingStatus,addedAt:now,updatedAt:now});await addActivity({type:"added",mangaId:manga.id,mangaTitle:manga.title,detail:"Added to library"});await write(entries);}return entries;}
export async function updateLibraryEntry(id:string,patch:Partial<Pick<LibraryEntry,"readingStatus"|"currentChapter">>){const entries=await read();const entry=entries.find(e=>e.manga.id===id);if(!entry)return entries;const chapterChanged=patch.currentChapter!==undefined&&patch.currentChapter!==entry.currentChapter;const statusChanged=patch.readingStatus!==undefined&&patch.readingStatus!==entry.readingStatus;if(!chapterChanged&&!statusChanged)return entries;const now=new Date().toISOString();const previousChapter=entry.currentChapter;const previousStatus=entry.readingStatus;Object.assign(entry,patch,{updatedAt:now});if(patch.currentChapter!==undefined&&patch.currentChapter!==previousChapter)await addActivity({type:"chapter_read",mangaId:id,mangaTitle:entry.manga.title,detail:"Read chapter "+patch.currentChapter,chapter:patch.currentChapter});if(patch.readingStatus!==undefined&&patch.readingStatus!==previousStatus)await addActivity({type:"status_changed",mangaId:id,mangaTitle:entry.manga.title,detail:"Status changed to "+patch.readingStatus});await write(entries);return entries;}
export async function removeFromLibrary(id:string){const entries=await read();const removed=entries.find(e=>e.manga.id===id);if(removed)await addActivity({type:"removed",mangaId:id,mangaTitle:removed.manga.title,detail:"Removed from library"});if(!removed)return entries;const next=entries.filter(e=>e.manga.id!==id);await write(next);return next;}
export async function clearLibrary(){await AsyncStorage.removeItem(KEY);}
export async function clearActivity(){await AsyncStorage.removeItem(ACTIVITY_KEY);}
